/*
 * This source file was generated by the Gradle 'init' task
 */
package org.gzs.design.gof

import spock.lang.Specification

class StrategyPatternSampleTest extends Specification {
    def "application has a greeting"() {
        setup:
        def app = new StrategyPatternSample()

        when:
        def result = app.greeting

        then:
        result != null
    }
}
