/*
 * This source file was generated by the Gradle 'init' task
 */
package org.gzs.design.gof;

public class StrategyPatternSample {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new StrategyPatternSample().getGreeting());
    }
}
